# monitoring/prometheus/prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    environment: local
    project:     ros2-devops

scrape_configs:
  # Scrape our robot application
  - job_name: robot-sensor-monitor
    static_configs:
      - targets: ["app:8080"]
    metrics_path: /metrics

  # Scrape Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
